version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=subscribers
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db  # This line mounts the volume
    command: mongod --auth --port 27017
volumes:
  mongodb_data:
